site_name: Tube4·(最新)官方网站
site_author: Tube4
site_description: Tube4是全球知名视频分享平台，提供高清视频播放、创作者社区和智能推荐服务，支持多设备同步和离线观看。
theme:
  name: readthedocs
nav:
  - Home: index.md
  - About: about.md
  - Features: features.md
  - Contact: contact.md
